# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: (container) Build and Deploy Logic App. 

env:
  RG_CON: 'delirg2'
  LA_NAME: 'lar2la'
  IMAGE_NAME: 'lar2acr'
  IMAGE_TAG: 'tag123'
  ACR_NAME: 'lar2acr'

on:
  - workflow_dispatch 

jobs:
   logic_app_build: 
    runs-on: ubuntu-latest
    steps: 

    - name: Checkout
      uses: actions/checkout@v1
    
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true 

     #build container image
    - name: Generate Connections
      uses: azure/powershell@v1
      with:
        inlineScript: |
          ./Scripts/Generate-Connections.ps1 -resourceGroup '${{ env.RG_CON }}'
        azPSVersion: latest

    - name: 'Login to Azure Container Registry'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.ACR_NAME }}.azurecr.io
        username: ${{ env.ACR_NAME }}
        password: ${{secrets.ACRPASSWORD}}

    - name: 'Build & Push Docker Image'
      shell: bash
      run: |
        docker build . -t  ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        docker push  ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

    - name: 'Deploy Logic App Container'
      uses: Azure/functions-container-action@v1
      id: fa
      with:
        app-name: ${{ env.LA_NAME }}
        image: '${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}'
